estados_to_ufs = {
    'ACRE': 'AC',
    'ALAGOAS': 'AL',
    'AMAPA': 'AP',
    'AMAZONAS': 'AM',
    'BAHIA': 'BA',
    'CEARA': 'CE',
    'DISTRITO FEDERAL': 'DF',
    'ESPIRITO SANTO': 'ES',
    'GOIAS': 'GO',
    'MARANHAO': 'MA',
    'MATO GROSSO': 'MT',
    'MATO GROSSO DO SUL': 'MS',
    'MINAS GERAIS': 'MG',
    'PARA': 'PA',
    'PARAIBA': 'PB',
    'PARANA': 'PR',
    'PERNAMBUCO': 'PE',
    'PIAUI': 'PI',
    'RIO DE JANEIRO': 'RJ',
    'RIO GRANDE DO NORTE': 'RN',
    'RIO GRANDE DO SUL': 'RS',
    'RONDONIA': 'RO',
    'RORAIMA': 'RR',
    'SANTA CATARINA': 'SC',
    'SAO PAULO': 'SP',
    'SERGIPE': 'SE',
    'TOCANTINS': 'TO'
}

ufs_to_estados = {
    'AC': 'ACRE',
    'AL': 'ALAGOAS',
    'AP': 'AMAPA',
    'AM': 'AMAZONAS',
    'BA': 'BAHIA',
    'CE': 'CEARA',
    'DF': 'DISTRITO FEDERAL',
    'ES': 'ESPIRITO SANTO',
    'GO': 'GOIAS',
    'MA': 'MARANHAO',
    'MT': 'MATO GROSSO',
    'MS': 'MATO GROSSO DO SUL',
    'MG': 'MINAS GERAIS',
    'PA': 'PARA',
    'PB': 'PARAIBA',
    'PR': 'PARANA',
    'PE': 'PERNAMBUCO',
    'PI': 'PIAUI',
    'RJ': 'RIO DE JANEIRO',
    'RN': 'RIO GRANDE DO NORTE',
    'RS': 'RIO GRANDE DO SUL',
    'RO': 'RONDONIA',
    'RR': 'RORAIMA',
    'SC': 'SANTA CATARINA',
    'SP': 'SAO PAULO',
    'SE': 'SERGIPE',
    'TO': 'TOCANTINS'
}


estados_compostos = [
    'espirito santo',
    'mato grosso',
    'mato grosso do sul',
    'minas gerais',
    'rio de janeiro',
    'rio grande do norte',
    'rio grande do sul',
    'santa catarina',
    'são paulo',
    'distrito federal'
]

space_demarker = '<%>'

setores = {
    'Agricultura', 'Pecuaria', 'Pesca', 'Silvicultura', 'Mineracao',
    'Petroleo e Gas', 'Energia', 'Construcao Civil', 'Engenharia',
    'Manufatura', 'Industria Automotiva', 'Industria Naval', 'Industria Aeroespacial',
    'Industria Quimica', 'Industria Farmaceutica', 'Industria Textil', 'Industria de Alimentos',
    'Tecnologia da Informacao', 'Desenvolvimento de Software', 'Hardware', 'Ciberseguranca',
    'Inteligencia Artificial', 'Robotica', 'Eletronica', 'Telecomunicacoes',
    'Biotecnologia', 'Nanotecnologia', 'Saude', 'Medicina', 'Enfermagem', 'Odontologia',
    'Veterinaria', 'Educacao', 'Educacao Infantil', 'Ensino Fundamental', 'Ensino Medio',
    'Ensino Superior', 'Pesquisa Cientifica', 'Psicologia', 'Servico Social',
    'Direito', 'Justica', 'Administracao Publica', 'Defesa Nacional', 'Seguranca Publica',
    'Policia', 'Bombeiros', 'Logistica', 'Transporte Rodoviario', 'Transporte Ferroviario',
    'Transporte Aereo', 'Transporte Maritimo', 'Mobilidade Urbana', 'Comercio',
    'E-commerce', 'Varejo', 'Atacado', 'Mercado Financeiro', 'Bancos', 'Corretoras',
    'Seguros', 'Contabilidade', 'Recursos Humanos', 'Consultoria', 'Publicidade',
    'Marketing', 'Turismo', 'Hotelaria', 'Alimentacao', 'Gastronomia', 'Eventos',
    'Artes', 'Musica', 'Cinema', 'Teatro', 'Design', 'Arquitetura', 'Moda',
    'Esportes', 'Lazer', 'Jogos Digitais', 'Streaming', 'Midia', 'Jornalismo',
    'Relacoes Publicas', 'Ecologia', 'Meio Ambiente', 'Gestao Ambiental', 'Reciclagem',
    'Saneamento', 'Tratamento de Agua', 'Gestao de Residuos', 'Organizacoes Nao Governamentais',
    'Religiao', 'Servicos Domesticos', 'Servicos Gerais', 'Servicos Tecnicos',
    'Startups', 'Empreendedorismo', 'Inovacao', 'Economia Criativa', 'Economia Circular',
    'Criptomoedas', 'Blockchain', 'Metaverso', 'Educacao Corporativa', 'Treinamento Profissional',
    'Deficiencia e Inclusao', 'Tecnologia Assistiva', 'Agronegocio', 'Cooperativas',
    'Energia Renovavel', 'Energia Solar', 'Energia Eolica', 'Hidreletricas', 'Nuclear',
    'Planejamento Urbano', 'Engenharia de Trafego', 'Engenharia de Producao',
    'Engenharia Ambiental', 'Engenharia Biomedica', 'Geociencias', 'Meteorologia', 'Oceanografia'
}


sinonimos_empresa = [
    'companhia',
    'corporação',
    'firma',
    'negócio',
    'organização',
    'entidade',
    'estabelecimento',
    'instituição',
    'sociedade',
    'grupo empresarial',
    'conglomerado',
    'associação',
    'emprendimento',
    'startup',
    'indústria',
    'cooperativa',
    'agência',
    'consultoria',
    'holding',
    'empresa'
]


sinonimos_setor = [
    'no departamento',
    'na divisão',
    'na área',
    'no segmento',
    'no ramo',
    'na unidade',
    'na seção',
    'com núcleo',
    'na esfera',
    'no domínio',
    'na categoria',
    'no campo',
    'com a especialidade',
    'na atividade',
    'na verticalidade',
    'na linha de negócio',
    'no pólo',
    'na zona',
    'no setor'
]


sinonimos_porte = [
    'tamanho',
    'dimensão',
    'capacidade',
    'envergadura',
    'estrutura',
    'escala',
    'volume',
    'potência',
    'vulto',
    'importância',
    'estatura',
    'proporção',
    'composição',
    'perfil',
    'categoria',
    'classe',
    'tipo',
    'porte'
]


sinonimos_funcionarios = [
    "colaboradores",
    "empregados",
    "servidores",
    "trabalhadores",
    "pessoas",
    "funcionarios",
    "de corpo funcional",
    "de quadro de pessoas",
    "operários",
    "membros na equipe",
    "assistentes",
    "prestadores",
    "auxiliares",
    "de mão de obra",
    "integrantes",
    "de staff",
    "profissionais",
]
